---

extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack
  react:
    version: require('./package.json').dependencies.react

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
